#!/bin/bash

# Modified from script found here: https://blog.dhampir.no/content/fixing-shmget-failed-no-space-left-on-device
cleanup.shared_memory () {
    # shellcheck disable=SC2162
    while read key id owner nattch; do
        if [[ -z $key ]] || [[ -z $id ]] || [[ -z $owner ]]; then
            errcho "Ignoring invalid line from ipcs: [${key} ${id} ${owner} ${nattch}]"
            continue
        fi

        local output
        if output=$(sudo ipcrm shm "$id" 2>&1); then
            gerrcho "Cleanup shared memory: removed [${key} ${id} ${owner} ${nattch}]"
        else
            errcho "Failed to delete line from ipcs: [${key} ${id} ${owner} ${nattch}]"
            errcho "Output given: [${output}]"
        fi
    done < <(sudo ipcs -m | grep "^0x" | awk '{print $1, $2, $3, $6}' | grep " 0$")
}
