#!/bin/bash
import errcho

rerrcho "BUG: z5.stdlib import() is broken, because it only imports any lib once, \
without checking for the presence of import parameters e.g. cleanup DEBUG"

# =============================
declare -g __debug_cleanup; __debug_cleanup=0
declare -g __cleanup_trap_is_set; __cleanup_trap_is_set=0

# the -g, and empty array assignment, are required
declare -ag __cleanup_on_exit_items; __cleanup_on_exit_items=()
# declare -ag __cleanup_on_error_items; __cleanup_on_error_items=()

declare -g __cleanup_on_exit_last; __cleanup_on_exit_last=

__in_cleanup_rc=
# =============================


cleanup._import () {
    local debug_setting; debug_setting="${1:-0}"

    ((__cleanup_trap_is_set == 0)) && { trap cleanup._on_exit EXIT; __cleanup_trap_is_set=1; }

    ((__debug_cleanup == 1)) && return

    [[ $debug_setting == DEBUG ]] && __debug_cleanup=1
    [[ $debug_setting -eq 1 ]]    && __debug_cleanup=1
    :
}

cleanup._import "$@"

# https://riptutorial.com/bash/example/2398/accumulate-a-list-of-trap-work-to-run-at-exit-
# Usage:
#   cleanup.add rm -f /tmp/foo
#   cleanup.add echo "I am exiting"
#   tempfile=$(mktemp)
#   cleanup.add rm -f "$tempfile"
# Based on http://www.linuxjournal.com/content/use-bash-trap-statement-cleanup-temporary-files

# ! IMPORTANT - don't use logical operators in the cleanup string, they will be
# ! executed in real time. Wrap them in a subroutine and call the subroutine in
# ! the cleanup.add or cleanup.error.add

# functions running during cleanup can call this to retrieve the rc
cleanup.rc () {
    printf '%s' "$__in_cleanup_rc"
}

cleanup._on_exit () {
    # In general, a cleanup function (called via 'trap') will leave $? unmodified,
    # and we don't need to call exit at the end. But since we are executing
    # arbitrary code, we make sure to preserve rc in case someone else modifies
    # it by accident in an exit item.
    local rc=$? # do NOT separate declaration from assignment - $? becomes the rc from 'local rc;'!!!

    __in_cleanup_rc="$rc"

    [[ -n $__cleanup_on_exit_last ]] && __cleanup_on_exit_items+=("$__cleanup_on_exit_last")

    nostrict
    ((__debug_cleanup == 1)) && berrcho "===== Running EXIT cleanup for $0 ====="

    for i in "${__cleanup_on_exit_items[@]}"
    do
        ((__debug_cleanup == 1)) && berrcho "CLEANUP: $i"
        eval "$i"
    done

    exit "$rc"
}

# cleanup._on_error () {
#     local rc=$?

#     nostrict
#     berrcho "===== Running ERROR ($rc) cleanup for $0 ====="

#     for i in "${__cleanup_on_error_items[@]}"
#     do
#         eval "$i"
#     done

#     exit "$rc"
# }

cleanup.add () {
    local -i n; n="${#__cleanup_on_exit_items[@]}"
    local IFS=$' \n\t'
    # gerrcho "Adding cleanup: " "$@"
    __cleanup_on_exit_items[$n]="$*"
    # [[ $n -eq 0 ]] && trap cleanup._on_exit EXIT
    :
}

cleanup.last () {
    [[ -n $__cleanup_on_exit_last ]] && errxit "ERROR: cleanup.last can only be called once"
    __cleanup_on_exit_last="$*"
}

# cleanup.error.add () {
#     local -i n; n="${#__cleanup_on_error_items[@]}"
#     local IFS=$' \n\t'
#     # gerrcho "Adding cleanup: " "$@"
#     __cleanup_on_error_items[$n]="$*"
#     [[ $n -eq 0 ]] && trap cleanup._on_error ERR
#     :
# }

# Modified from script found here: https://blog.dhampir.no/content/fixing-shmget-failed-no-space-left-on-device
# This has some basic info: https://linoxide.com/how-tos/command-to-show-shared-memory-settings/
cleanup._shared_memory () {
    local user; user="$1"

    # shellcheck disable=SC2162
    while read key id owner nattch
    do
        if [[ -z $key ]] || [[ -z $id ]] || [[ -z $owner ]]; then
            echo "Ignoring invalid line from ipcs: [${key} ${id} ${owner} ${nattch}]" >&2
            continue
        fi

        local output
        if output=$(ipcrm shm "$id" 2>&1)
        then
            echo "Cleanup shared memory: removed [${key} ${id} ${owner} ${nattch}]" >&2
        else
            echo "Failed to delete line from ipcs: [${key} ${id} ${owner} ${nattch}]" >&2
            echo "Output given: [${output}]" >&2
        fi
    done < <(ipcs -m | grep "^0x" | awk '{print $1, $2, $3, $6}' | grep " 0$" | grep "$user")
}

cleanup.shared_memory () {
    if test.i_can_sudo_root
    then
        local func; func=$(declare -f cleanup._shared_memory)
        sudo bash -c "$func; cleanup._shared_memory root"
    fi

    cleanup.my_shared_memory
}

cleanup.my_shared_memory () {
    cleanup._shared_memory "$USER"
}


:
