#!/bin/bash

PAUSE=${PAUSE:-0}
DEBUG=${DEBUG:-0}
PAUSE_DEBUG=${PAUSE_DEBUG:-1}

# For coloured output see https://stackoverflow.com/a/20983251/2334574
# tput setab [1-7] # Set the background colour using ANSI escape
# tput setaf [1-7] # Set the foreground colour using ANSI escape

# Colours are as follows:

# Num  Colour    #define         R G B

# 0    black     COLOR_BLACK     0,0,0
# 1    red       COLOR_RED       1,0,0
# 2    green     COLOR_GREEN     0,1,0
# 3    yellow    COLOR_YELLOW    1,1,0
# 4    blue      COLOR_BLUE      0,0,1
# 5    magenta   COLOR_MAGENTA   1,0,1
# 6    cyan      COLOR_CYAN      0,1,1
# 7    white     COLOR_WHITE     1,1,1

# errxit "the foobar failed" 2
errxit() {
    local message="$1"
    local rc="${2:-1}"

    # shellcheck disable=SC2046
    set $(caller 0)
    line=$1; subroutine=${2:-}; filename=${3:-}

    rerrcho "ERROR at line $line in ${subroutine}() of $filename: $message [$rc]"

    exit "$rc"
}

errcho () {
    if [[ -z $1 ]]; then
        echo >&2
        return 0
    fi

    if [[ $1 == -n ]]; then
        shift
        printf "[%s]: %s" "$(date +'%Y-%m-%d_%H:%M:%S')" "$*" >&2;
    else
        printf "[%s]: %s\n" "$(date +'%Y-%m-%d_%H:%M:%S')" "$*" >&2;
    fi
}

# echo first, to set the colour before errcho adds the timestamp prefix
# yerrcho () { echo -n "${YELLOW}" >&2;  errcho "$1${RESET}"; }
# rerrcho () { echo -n "${RED}" >&2;     errcho "$1${RESET}"; }
# gerrcho () { echo -n "${GREEN}" >&2;   errcho "$1${RESET}"; }
# berrcho () { echo -n "${BLUE}" >&2;    errcho "$1${RESET}"; }
# merrcho () { echo -n "${MAGENTA}" >&2; errcho "$1${RESET}"; }
# cerrcho () { echo -n "${CYAN}" >&2;    errcho "$1${RESET}"; }

errchoRED=1; errchoGREEN=2; errchoYELLOW=3; errchoBLUE=4; errchoMAGENTA=5; errchoCYAN=6; # WHITE=7;

rerrcho () { _colour_errcho $errchoRED     "$@"; }
gerrcho () { _colour_errcho $errchoGREEN   "$@"; }
yerrcho () { _colour_errcho $errchoYELLOW  "$@"; }
berrcho () { _colour_errcho $errchoBLUE    "$@"; }
merrcho () { _colour_errcho $errchoMAGENTA "$@"; }
cerrcho () { _colour_errcho $errchoCYAN    "$@"; }

_colour_errcho () {
    local -i colour; colour="$1"
    shift

    if [[ -n $TERM ]] && [[ $TERM != dumb ]]; then
        local colseq; colseq="$(tput setaf "$colour")"
        local reset; reset="$(tput sgr0)"

        echo -n "${colseq}" >&2; errcho "$@" "${reset}"
    else
        errcho "$@"
    fi
}

recho () { _colour_echo $errchoRED     "$1"; }
gecho () { _colour_echo $errchoGREEN   "$1"; }
yecho () { _colour_echo $errchoYELLOW  "$1"; }
becho () { _colour_echo $errchoBLUE    "$1"; }
mecho () { _colour_echo $errchoMAGENTA "$1"; }
cecho () { _colour_echo $errchoCYAN    "$1"; }

_colour_echo () {
    local -i colour; colour="$1"
    shift

    if [[ -n $TERM ]] && [[ $TERM != dumb ]]; then
        local colseq; colseq="$(tput setaf "$colour")"
        local reset; reset="$(tput sgr0)"

        echo -n "${colseq}"; echo "$@" "${reset}"
    else
        echo "$@"
    fi
}

debug () { [[ $DEBUG -eq 1 ]] && yerrcho "${FUNCNAME[1]}: $*"; return 0; }

pause () {
    [[ $PAUSE == 1 ]] && local PAUSE_DEBUG=1

    [[ -n $1 && $PAUSE_DEBUG == 1 ]] && gerrcho "$1"

    [[ $PAUSE == 0 ]] && return 0

    read -n 1 -s -r -p "Press any key to continue"

    errcho
}

pause_fn () {
    local msg; msg="${1:-}"
    pause ": ${FUNCNAME[1]}() $msg"
}
