#!/bin/bash

import pathtools

# Add an entry to the .gitignore file of the current repo
git.ignore () {
    local rootdir; rootdir="$(path.their.rootdir .gitignore)"
    local gitignore; gitignore="$rootdir/.gitignore"
    local path; path="$1"

    grep "^$path$" "$gitignore" > /dev/null || echo "$path" >> "$gitignore"
}
