#!/usr/bin/bash

if [[ -n ${1:-} && $1 == strict ]]; then
    # saner programming env: these switches turn some bugs into errors
    set -o errexit
    set -o nounset
    set -o pipefail
    #set -o noclobber
fi

# https://unix.stackexchange.com/questions/4650/determining-path-to-sourced-shell-script

# don't put this inside functions, it'll get it wrong (see link)
_z5stdlibshdir="$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )"
_z5stdlibdir="$(dirname "$_z5stdlibshdir")"

_stdlib_self_update () {(
    cd "$_z5stdlibdir"
    # git is installed; the current user owns this file; stdlibdir is in a git repo
    if which git > /dev/null && [[ -O ${BASH_SOURCE[0]} ]] && git rev-parse 2> /dev/null ; then
        git pull > /dev/null
    fi
)}

_stdlib_self_update

# import somelib
import () {
    local lib; lib="$1"

    declare -A imported

    if [[ -f "$_z5stdlibshdir/$lib" ]]; then
        [[ -n ${imported[$lib]+x} ]] && [[ ${imported[$lib]} -eq 1 ]] && return 0

        # shellcheck disable=SC1090
        source "$_z5stdlibshdir/$lib"
        imported[$lib]=1
        return 0
    else
        echo "ERROR: Library '$lib' not found in $_z5stdlibshdir" >&2
        return 1
    fi
}

# refactor this when I get the chance. Not using it for anything yet.
import.utils () {
    local lib; lib="$1"
    local _z5utilsshdir; _z5utilsshdir="$(dirname "$_z5stdlibdir")/z5.utils/sh"

    declare -A imported_utils

    if [[ -f "$_z5utilsshdir/$lib" ]]; then
        [[ -n ${imported_utils[$lib]+x} ]] && [[ ${imported_utils[$lib]} -eq 1 ]] && return 0

        # shellcheck disable=SC1090
        source "$_z5utilsshdir/$lib"
        imported_utils[$lib]=1
        return 0
    else
        echo "ERROR: Library '$lib' not found in $_z5utilsshdir" >&2
        return 1
    fi
}
