#!/usr/bin/bash

# https://unix.stackexchange.com/questions/4650/determining-path-to-sourced-shell-script

# don't put this inside the function, it'll get it wrong (see link)
_importer_source_dir="$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )"

# import somelib
import () {
    local lib; lib="$1"
    local libdir; libdir="$_importer_source_dir"
    
    declare -A imported

    if [[ -f "$libdir/$lib" ]]; then 
        [[ ${imported[$lib]} -eq 1 ]] && return 0

        # shellcheck disable=SC1090
        source "$libdir/$lib"
        imported[$lib]=1
        return 0
    else
        echo "ERROR: Library '$lib' not found in $libdir" >&2
        return 1
    fi
}
