#!/bin/bash
import errcho

# Pass '--quiet' as first arg to silence the warning about no /proc/$pid
stop.pid () {
    local opt_quiet=0

    if (($# == 2))
    then
        [[ $1 == "--quiet" ]] || { errcho "Unknown option: $1"; return 1; }
        opt_quiet=1
        shift
    fi

    local pid; pid="$1"
    [[ -z $pid ]] && { errcho "WARNING: ${FUNCNAME[0]} expects a PID"; return 0; }

    if ! [[ -d /proc/$pid ]]
    then
        ((opt_quiet != 1)) && errcho "WARNING: no /proc/$pid to stop"
        return 0
    fi

    errcho "Stopping PID $pid - command was: $(pid.command "$pid")"

    # shellcheck disable=SC2046,SC2086
    kill -term $pid $(list.descendants $pid) || :

    # give it up to 5 seconds to gracefully shut down
    local i=0
    while [[ -d /proc/$pid ]]
    do
        sleep 0.1
        ((i=i+1))

        ((i == 50)) && break
    done

    # make sure of the job
    if [[ -d /proc/$pid ]]
    then
        # shellcheck disable=SC2046,SC2086
        kill -9 $pid $(list.descendants $pid) || :
    fi
}

pid.command () {
    ps --no-headers -o cmd --pid "$1" | perl -pe 's/ +/ /g'
}

list.descendants () {
    local children; children=$(ps -o pid= --ppid "$1")

    for pid in $children
    do
        list.descendants "$pid"
    done

    printf '%s\n' "$children"
}

list.descendants.comma_separated () {
    list.descendants "$1" | tr '\n' ',' | sed 's/,\+/,/g' | sed 's/\s\+//g' | sed 's/,$//'
}

pidfile.set () {
    local dir path pid; path="$1"; pid="$2"
    dir="$(dirname "$path")"
    mkdir -p "$dir"
    rm -f "$path"
    echo "$pid" > "$path"
}

pidfile.get () {
    cat < "$1"
}
