#!/bin/bash
import errcho
import pathtools

PoetRootDir=

poet._import () {
    poet.switchroot "$1"
    poet._build
}

# shellcheck disable=SC2128
__ptools_mydir="$(dirname "$BASH_SOURCE")"

poet.conf.get () {
    local keyspec; keyspec="$1"

    if [[ -z $keyspec ]]; then
        errcho "No key supplied"
        return 1
    fi

    "$__ptools_mydir/../docker/d.start.poet.conf.get" "$PoetRootDir" "$keyspec"
}

poet.switchroot () {
    PoetRootDir="$(readlink --canonicalize-existing "$1")"

    if [[ -z "$PoetRootDir" ]]; then
        errcho "No Poet root supplied on import"
        return 1
    fi

    if ! [[ -d "$PoetRootDir" ]]; then
        errcho "Supplied Poet root '$1' is not a directory"
        return 1
    fi
}

poet._build () {(
    cd "$__ptools_mydir/../docker/poet.conf.get" || return 1
    # TODO when debugging is done, put this on docker hub and pull the image instead
    docker build -t poet.conf.get . > /dev/null
)}

poet._import "$@"
