#!/bin/bash
import errcho
import pathtools

PoetRootDir=

poet._import () {
    local rootdir; rootdir="${1:-"$(path.rootdir.pwd .poet_root)"}"
    poet.switchroot "$rootdir"
    poet._build
}

poet.conf.get () {
    "$Z5STDLIB_HOME/docker/d.start.poet.conf.get" "$PoetRootDir" "$@"
}

poet.switchroot () {
    PoetRootDir="$(readlink --canonicalize-existing "$1")"

    if [[ -z "$PoetRootDir" ]]; then
        errcho "No Poet root supplied on import"
        return 1
    fi

    if ! [[ -d "$PoetRootDir" ]]; then
        errcho "Supplied Poet root '$1' is not a directory"
        return 1
    fi
}

poet._build () {(
    cd "$Z5STDLIB_HOME/docker/poet.conf.get" || return 1
    # TODO when debugging is done, put this on docker hub and pull the image instead
    docker build -t poet.conf.get . > /dev/null
)}

poet._import "$@"
