#!/bin/bash
import errcho
import checks

# will remove specified rule if $2 is empty
# Suggested labels: user_${username} or group_${groupname}
usertools.sudoer () {
    local label rule; label="$1"; rule="${2:-}"

    check.i_can_root
    which sudo > /dev/null || install.apt.pkgs sudo

    rm -f "/etc/sudoers.d/${label}"

    [[ -z $rule ]] && return 0

    echo "$rule" > "/etc/sudoers.d/${label}"
    chmod 0440 "/etc/sudoers.d/${label}"
}

# this works even if user is 'root'
usertools.homedir () {
    local user; user="${1:-$USER}"

    local homedir; homedir="$(eval echo "~$user")"

    if [[ -d $homedir ]]; then
        echo "$homedir"
        return 0
    fi

    errcho "Home dir '$homedir' for user '$user' does not exist"
    return 1
}

usertools.gid () {
    getent group "$1" | awk -F: '{printf "%d\n", $3}'
}
