#!/bin/bash
import errcho

vbox.fix_hostonly_networking () {
    [[ -f /etc/network/interfaces.d/vbox-host-only ]] && return 0

    {
        echo "allow-hotplug enp0s8"
        echo "iface enp0s8 inet dhcp"
    } > /etc/network/interfaces.d/vbox-host-only

    ifup enp0s8 > /dev/null 2>&1 || errxit "ifup enp0s8 failed" $?
}

test.is_vbox () (
    set +x
    [[ $(dmidecode -s system-manufacturer) == "innotek GmbH" ]]
)