#!/usr/bin/bash

import errcho 

# First arg: filename
# Optional second arg: timeout in 1/10 s (default 10 i.e. 1 second)

waitfor.socket () { waitfor.type "socket" "$@"; }
waitfor.file   () { waitfor.type "file"   "$@"; }

waitfor.type () {
    local type; type="$1"
    local file; file="$2"
    local c; c=0
    local cmax; cmax=${3:-10}

    while ! waitfor.exists "$type" "$file"
    do
        (( c++ )) || :
        sleep 0.1
        if [[ $c -gt $cmax ]]; then
            errxit "TIMEOUT: $type '$file' not created after $c/10 seconds" 1
        fi
    done

    return 0
}

waitfor.exists () {
    local type; type="$1"
    local file; file="$2"

    case $type in
        socket)
            [[ -S $file ]]
            ;;
        file)
            [[ -f $file ]]
            ;;
        *)
            errxit "$0: unknown type '$type'" 1
            ;;
    esac
}
