#!/bin/bash

import errcho

# First arg: filename
# Optional second arg: timeout in 1/10 s (default 10 i.e. 1 second)

waitfor.socket () { __waitfor_type "socket" "$@"; }
waitfor.file   () { __waitfor_type "file"   "$@"; }

waitfor.docker () { errxit "Use dockertools dtools.waitfor instead"; }

__waitfor_type () {
    local type; type="$1"
    local file; file="$2"
    local c; c=0
    local cmax; cmax=${3:-10}

    while ! __waitfor_exists "$type" "$file"
    do
        (( c++ )) || :
        sleep 0.1
        if [[ $c -gt $cmax ]]; then
            errcho "TIMEOUT: $type '$file' not created after $c/10 seconds"
            return 1
        fi
    done

    return 0
}

__waitfor_exists () {
    local type; type="$1"
    local file; file="$2"

    case $type in
        socket)
            [[ -S $file ]]
            ;;
        file)
            [[ -f $file ]]
            ;;
        *)
            errxit "$0: unknown type '$type'" 1
            ;;
    esac
}

waitfor.umount () {
    local mountpoint; mountpoint="$1"

    if ! mountpoint -q "$mountpoint"
    then
        errcho "$mountpoint is not a mount point"
        return 1
    fi

    errcho -n "Unmounting $mountpoint..."

    while : ; do
        umount "$mountpoint" 2> /dev/null && break

        errcho -n '.'
        sleep 1
    done

    errcho
}

waitfor.host.port () {
    "$Z5_STDLIB"/bin/wait-for-it --quiet --host="$1" --port="$2" --timeout="${3:-5}"
}
